In [36]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [37]:
df = pd.read_csv('D://Sem 2//python//Deep Learning//Multiple Regression//for categorical dataset//50_Startups.csv')
df.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [38]:
df.shape

(50, 5)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
R&D Spend          50 non-null float64
Administration     50 non-null float64
Marketing Spend    50 non-null float64
State              50 non-null object
Profit             50 non-null float64
dtypes: float64(4), object(1)
memory usage: 2.0+ KB

In [40]:
df.dtypes

R&D Spend          float64
Administration     float64
Marketing Spend    float64
State               object
Profit             float64
dtype: object

In [41]:
# checking the null values in the data set & print them in an ascending order
df.isnull().sum().sort_values(ascending=False)

Profit             0
State              0
Marketing Spend    0
Administration     0
R&D Spend          0
dtype: int64

In [42]:
df.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [45]:
#Import Label encoder to convert object 
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['State']= label_encoder.fit_transform(df['State'])

from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['R&D Spend']= label_encoder.fit_transform(df['R&D Spend'])

from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['Marketing Spend']= label_encoder.fit_transform(df['Marketing Spend'])

from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['Profit']= label_encoder.fit_transform(df['Profit'])

from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['Administration']= label_encoder.fit_transform(df['Administration'])

In [46]:
df.dtypes

R&D Spend          int64
Administration     int64
Marketing Spend    int64
State              int64
Profit             int64
dtype: object

In [47]:
df.head()

   R&D Spend  Administration  Marketing Spend  State  Profit
0         48              34               47      2      49
1         47              41               46      0      48
2         46              11               45      1      47
3         45              22               44      2      46
4         44               6               43      1      45

In [48]:
X = df.iloc[:, :-1]
X

    R&D Spend  Administration  Marketing Spend  State
0          48              34               47      2
1          47              41               46      0
2          46              11               45      1
3          45              22               44      2
4          44               6               43      1
5          42              10               42      2
6          43              39               10      0
7          41              38               40      1
8          39              40               39      2
9          40              14               38      0
10         36              15               24      1
11         35               7               25      0
12         33              28               26      1
13         32              33               27      0
14         38              47               28      1
15         37              24               29      2
16         28              23               30      0
17         34              37               31      2
18         31              17               32      1
19         30              44                0      2
20         26              16               34      0
21         29              45               35      2
22         24              25               36      1
23         22              13               37      1
24         27               9               13      2
25         19              35               12      0
26         25              36               11      1
27         23              30               41      2
28         21              49                9      1
29         20              43                8      2
30         17              18                7      1
31         16              42                6      2
32         18              31                5      0
33         15              12               23      1
34         14              48               22      0
35         13               5               21      2
36          9              27               20      1
37         12               0               19      0
38          5               2               18      2
39         11               3               17      0
40         10              21               16      0
41          8               4               15      1
42          7               8               14      0
43          4              29                3      2
44          6              46                2      0
45          2              26                1      2
46          3              19               33      1
47          0              32                0      0
48          1               1                0      2
49          0              20                4      0

In [49]:
Y = df.iloc[:, 4]
Y

0     49
1     48
2     47
3     46
4     45
5     44
6     43
7     42
8     41
9     40
10    39
11    38
12    37
13    36
14    35
15    34
16    33
17    32
18    31
19    30
20    29
21    28
22    27
23    26
24    25
25    24
26    23
27    22
28    21
29    20
30    19
31    18
32    17
33    16
34    15
35    14
36    13
37    12
38    11
39    10
40     9
41     8
42     7
43     6
44     5
45     4
46     3
47     2
48     1
49     0
Name: Profit, dtype: int64

In [52]:
from sklearn.cross_validation import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [53]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [54]:
regressor.coef_

array([ 0.96461114,  0.00238432,  0.04688279, -0.38881748])

In [55]:
print(regressor.intercept_)

0.8799036408773908

In [56]:
Y_pred = regressor.predict(X_test)
print(Y_pred)
df = pd.DataFrame(Y_test,Y_pred)
print(df)

[21.28669707 35.83005381 36.37803924  8.92075452 46.99915209 24.28204922
  5.77398335 15.91748524 25.38914226 44.96424261]
           Profit
21.286697     NaN
35.830054     NaN
36.378039     NaN
8.920755      NaN
46.999152     NaN
24.282049     NaN
5.773983      NaN
15.917485     NaN
25.389142     NaN
44.964243     NaN

In [57]:
regressor.score(X_test,Y_test)

0.9702101942668738

In [58]:
#import statsmodel.api as sm
from statsmodels import api as sm
from sklearn.model_selection import train_test_split

x = sm.add_constant(df)
y = df['Profit']

In [59]:
#Dividing the data into training and testing data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [60]:
#Printing the model summary and checking the p values for significant values
df1 = sm.OLS(Y_train, X_train).fit()
df1.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.995
Model:                            OLS   Adj. R-squared:                  0.994
Method:                 Least Squares   F-statistic:                     1791.
Date:                Tue, 19 Nov 2019   Prob (F-statistic):           7.21e-41
Time:                        00:22:31   Log-Likelihood:                -83.889
No. Observations:                  40   AIC:                             175.8
Df Residuals:                      36   BIC:                             182.5
Df Model:                           4
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
R&D Spend           0.9609      0.036     26.483      0.000       0.887       1.035
Administration      0.0191      0.020      0.940      0.353      -0.022       0.060
Marketing Spend     0.0606      0.032      1.919      0.063      -0.003       0.125
State              -0.2633      0.367     -0.717      0.478      -1.008       0.481
==============================================================================
Omnibus:                        0.936   Durbin-Watson:                   1.931
Prob(Omnibus):                  0.626   Jarque-Bera (JB):                0.941
Skew:                           0.216   Prob(JB):                        0.625
Kurtosis:                       2.386   Cond. No.                         50.0
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [73]:
#Running the vif factor to remove the insignificant values
from statsmodels.stats.outliers_influence import variance_inflation_factor
X = np.append(arr = np.ones((50, 1)).astype(int), values = X, axis = 1)

In [79]:
x_opt = X[:, [0, 1, 2, 3, 4]]
regressor_OLS = sm.OLS(endog = Y, exog = x_opt).fit()
#df1 = sm.OLS(Y_train, X_train).fit()

In [80]:
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.981
Model:                            OLS   Adj. R-squared:                  0.979
Method:                 Least Squares   F-statistic:                     580.9
Date:                Tue, 19 Nov 2019   Prob (F-statistic):           4.30e-38
Time:                        00:38:01   Log-Likelihood:                -105.33
No. Observations:                  50   AIC:                             220.7
Df Residuals:                      45   BIC:                             230.2
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.5157      0.832      1.823      0.075      -0.159       3.191
x1             0.9741      0.032     30.852      0.000       0.911       1.038
x2            -0.0150      0.022     -0.674      0.504      -0.060       0.030
x3             0.0322      0.031      1.030      0.309      -0.031       0.095
x4            -0.2856      0.362     -0.789      0.434      -1.015       0.444
==============================================================================
Omnibus:                        1.915   Durbin-Watson:                   2.510
Prob(Omnibus):                  0.384   Jarque-Bera (JB):                1.685
Skew:                           0.323   Prob(JB):                        0.431
Kurtosis:                       2.374   Cond. No.                         127.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [82]:
X_opt = X[:, [0, 1,]]
regressor_OLS = sm.OLS(endog = Y, exog = X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 Profit   R-squared:                       0.980
Model:                            OLS   Adj. R-squared:                  0.979
Method:                 Least Squares   F-statistic:                     2328.
Date:                Tue, 19 Nov 2019   Prob (F-statistic):           2.47e-42
Time:                        00:40:38   Log-Likelihood:                -106.86
No. Observations:                  50   AIC:                             217.7
Df Residuals:                      48   BIC:                             221.6
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          1.1649      0.567      2.054      0.045       0.025       2.305
x1             0.9921      0.021     48.251      0.000       0.951       1.033
==============================================================================
Omnibus:                        1.229   Durbin-Watson:                   2.466
Prob(Omnibus):                  0.541   Jarque-Bera (JB):                1.255
Skew:                           0.330   Prob(JB):                        0.534
Kurtosis:                       2.593   Cond. No.                         52.9
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
# We see that only R&D is significant while decinding the price 
# R&D spending will give you the best sense of what a company profit will look like